#!/bin/bash
#
# This is a very basic docker smoke test. Simply launch a docker image and verify
# that it started.
#
set -x

export http_proxy=""
if echo "" | nc -w 2 squid.internal 3128 >/dev/null 2>&1; then
    echo "Running in the Canonical CI environment"
    export http_proxy="http://squid.internal:3128"
elif echo "" | nc -w 2 10.245.64.1 3128 >/dev/null 2>&1; then
    echo "Running in the Canonical enablement environment"
    export http_proxy="http://10.245.64.1:3128"
elif echo "" | nc -w 2 91.189.89.216 3128 >/dev/null 2>&1; then
    echo "Running in the Canonical enablement environment"
    export http_proxy="http://91.189.89.216:3128"
fi

if [ -n "$http_proxy" ]; then
    command -v systemctl &> /dev/null
    if [ $? -eq 0 ]; then
        [ ! -d /etc/systemd/system/docker.service.d ] && mkdir /etc/systemd/system/docker.service.d
        echo -e "[Service]\nEnvironment=HTTP_PROXY=$http_proxy\n" > /etc/systemd/system/docker.service.d/http-proxy.conf
        systemctl daemon-reload
        systemctl restart docker
    else
        echo "export http_proxy=\"$http_proxy\"" >> /etc/default/docker
        service docker restart
    fi
fi

release="bionic"
image="`uname -m`/ubuntu"
[ "`uname -m`" = "x86_64" ] && image="ubuntu"
# i386 is an official repository on docker.io, i686 is not
[ "`uname -m`" = "i686" ] && image="i386/ubuntu"
image="$image:$release"
RESULT=`sudo docker run $image /bin/sh -c "cat /etc/lsb-release | grep CODENAME | cut -d '=' -f 2"`
if [ "$RESULT" != "$release" ]; then
    echo "** ERROR: The codename returned from lsb_release -c was (" $RESULT ") and we were expecting $release"
    exit 1
fi
