#!/bin/bash
#
# This is the most basic of kvm tests. It just verifies that the
# installed host can launch a kvm instance and that we can get
# the lsb_release -c from that instance.
#
set -x
SUT=bjf-test
SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet"
DISTRO="xenial"

# Generate an ssh key so we can run commands on the KVM instance that we
# create.
#
ssh-keygen -f /home/ubuntu/.ssh/id_rsa -t rsa -N ''

# Download a release image that can be used to create the KVM instance.
#
uvt-simplestreams-libvirt sync release=$DISTRO arch=amd64

uvt-kvm create $SUT release=$DISTRO arch=amd64
uvt-kvm wait $SUT --insecure
ssh $SSH_OPTIONS ubuntu@`uvt-kvm ip $SUT` uname -a
RESULT=`ssh $SSH_OPTIONS ubuntu@\`uvt-kvm ip $SUT\` lsb_release -c | cut -d$'\t' -f 2`
if [ "$RESULT" != "$DISTRO" ]; then
    echo "** ERROR: The codename returned from lsb_release -c was (" $RESULT ") and we were expecting '$DISTRO'"
    exit 1
fi
uvt-kvm destroy $SUT
