#!/bin/sh
#

SD=qa-regression-testing/scripts
bzr branch lp:qa-regression-testing
tar jcvf ubuntu_qrt_kernel_aslr_collisions.tar.bz2 $SD/testlib.py $SD/test-kernel-aslr-collisions.py $SD/kernel-aslr-collisions
