#!/usr/bin/env python
#

import platform

if __name__ == '__main__':
    arch   = platform.processor()
    series = platform.dist()[2]

    pkgs = [
        'build-essential',
    ]
    gcc = 'gcc' if arch in ['ppc64el', 'aarch64'] else 'gcc-multilib'
    pkgs.append(gcc)

    print(' '.join(pkgs))

# vi:set ts=4 sw=4 expandtab syntax=python:
