#!/bin/sh
#

SD=qa-regression-testing/scripts
bzr branch lp:qa-regression-testing
(cd qa-regression-testing;bzr log > scripts/bzr.log)
(cd qa-regression-testing;bzr log scripts/test-kernel-hardening.py > scripts/test-hardening.py.log)
tar jcvf ubuntu_qrt_kernel_hardening.tar.bz2 $SD/bzr.log $SD/testlib.py $SD/test-kernel-hardening.py $SD/kernel-hardening 
