#!/usr/bin/env python
#

import platform

if __name__ == '__main__':
    arch   = platform.processor()
    series = platform.dist()[2]

    pkgs = [
        'pyflakes',
        'libcap2-bin',
        'gawk',
        'execstack',
        'exim4',
        'libcap-dev',
        'python-pexpect',
        'apparmor',
        'apparmor-utils',
        'netcat',
        'sudo',
        'libapparmor-dev',
        'attr',
        'apport',
        'libpam-apparmor',
        'libgtk2.0-dev',
        'apparmor-profiles',
        'quilt',
        'libdbus-1-dev',
        'python3',
        'python3-all-dev',
        'python-libapparmor',
    ]
    gcc = 'gcc' if arch in ['ppc64el', 'aarch64'] else 'gcc-multilib'
    pkgs.append(gcc)

    if series == 'precise':
        for p in ['ruby1.8']:
            pkgs.append(p)
    else:
        for p in ['python3-libapparmor', 'ruby', 'apparmor-easyprof']:
            pkgs.append(p)

    print(' '.join(pkgs))

# vi:set ts=4 sw=4 expandtab syntax=python:
