#!/bin/sh
#

SD=qa-regression-testing/scripts
bzr branch lp:qa-regression-testing
(cd qa-regression-testing;bzr log > scripts/bzr.log)
tar jcvf ubuntu-qrt-apparmor.tar.bz2 $SD/bzr.log $SD/testlib.py $SD/test-apparmor.py $SD/apparmor
