#!/bin/bash
# https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1056078
# Depends: coreutils, apparmor
PWD=`pwd`
cp /bin/sleep ./sleep1
./sleep1 10000000 < ./sleep1 &
for i in $(seq 1 1000); do
	echo "${PWD}/sleep1 { /** mrwk, }" | apparmor_parser -r > /dev/null 2>&1
done
# Cleanup
echo "${PWD}/sleep1 { /** mrwk, }" | apparmor_parser -R > /dev/null
trap 'exit 0' TERM
kill $(pidof sleep1)
rm sleep1
