#!/bin/bash
# https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1256988
# Depends: iproute2

set -e # Exit with a non-zero exit code if any errors occure

function cleanup {
    ip netns del foobar
}
trap cleanup EXIT

ip netns add foobar
ip netns exec foobar iptables -A OUTPUT -m recent --rcheck --rsource
