#!/bin/sh
#

SD=qa-regression-testing/scripts
bzr branch lp:qa-regression-testing
tar jcvf qrt.tar.bz2 $SD/testlib.py $SD/test-kernel-hardening.py $SD/kernel-hardening $SD/test-kernel.py $SD/kernel $SD/test-kernel-aslr-collisions.py $SD/kernel-aslr-collisions $SD/test-kernel-panic.py $SD/kernel-panic $SD/test-kernel-security.py $SD/kernel-security $SD/test-apparmor.py $SD/apparmor
