#!/usr/bin/env python
#

import platform

if __name__ == '__main__':
    arch   = platform.processor()
    series = platform.dist()[2]

    pkgs = [
        'build-essential',
        'uuid-dev',
        'xfslibs-dev',
        'xfsdump',
        'autoconf',
        'kpartx',
        'libtool',
        'python-xattr',
        'libacl1-dev',
        'libaio-dev',
        'quota',
        'bc',
        'btrfs-tools',
        'attr',
    ]
    gcc = 'gcc' if arch in ['ppc64el', 'aarch64'] else 'gcc-multilib'
    pkgs.append(gcc)

    if series in ['xenial', 'wily', 'vivid']:
        pkgs.append('libtool-bin')

    if series in ['wily', 'vivid']:
        pkgs.append('libdm0-dev')

    print(' '.join(pkgs))

# vi:set ts=4 sw=4 expandtab syntax=python:
